sudo: false

cache:
  directories:
  - $HOME/.composer/cache

language: php

env:
  global:
  - COVERAGE=0

matrix:
  include:
  - php: 7.1
    env: LARAVEL='5.4.*''
  - php: 7.1
    env: LARAVEL='5.5.*'
  - php: 7.1
    env: LARAVEL='5.6.*'
  - php: 7.1
    env: COVERAGE=1 LARAVEL='5.7.*'
  fast_finish: true

before_install:
- phpenv config-rm xdebug.ini
- composer global require hirak/prestissimo --update-no-dev
- composer require
  "illuminate/contracts:${LARAVEL}"
  "illuminate/http:${LARAVEL}"
  "illuminate/pagination:${LARAVEL}"
  "illuminate/routing:${LARAVEL}"
  "illuminate/support:${LARAVEL}"
  "illuminate/validation:${LARAVEL}"
  "orchestra/testbench:${LARAVEL/5\./3\.}"
  --no-interaction --no-update

install:
- composer install --prefer-dist --no-interaction --no-suggest

script:
- if [[ $COVERAGE = 1 ]]; then
    phpdbg -qrr phpunit --colors=always --verbose --coverage-text --coverage-clover=coverage.xml;
  else
    phpunit --colors=always --verbose;
  fi

after_success:
- if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
