sudo: false

cache:
  directories:
  - $HOME/.composer/cache

language: php

env:
  global:
  - COVERAGE=0

matrix:
  include:
  - php: 7.1
    env: LARAVEL='5.4.*''
  - php: 7.1
    env: LARAVEL='5.5.*'
  - php: 7.1
    env: LARAVEL='5.6.*'
  - php: 7.1
    env: COVERAGE=1 LARAVEL='5.7.*'
  fast_finish: true

before_install:
- phpenv config-rm xdebug.ini
- travis_retry composer global require hirak/prestissimo --update-no-dev
- travis_retry composer require "illuminate/contracts:${LARAVEL}" "illuminate/http:${LARAVEL}" "illuminate/pagination:${LARAVEL}" "illuminate/routing:${LARAVEL}" "illuminate/support:${LARAVEL}" "illuminate/validation:${LARAVEL}" --no-interaction --no-update

install:
- travis_retry composer install --prefer-dist --no-interaction --no-suggest

script:
- if [[ $COVERAGE = 1 ]]; then
    phpdbg -qrr phpunit --colors=always --verbose --coverage-text --coverage-clover=coverage.xml
  else
    phpunit --colors=always --verbose --coverage-text --coverage-clover=coverage.xml
  fi

after_success:
- if [[ $COVERAGE = 1 ]]; then bash <(curl -s https://codecov.io/bash); fi
